version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "npm run debug"
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules/
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
